- name: print parameter from parameter store
  hosts: local host
  connection: local
  tasks:
    - name: print parameter
      ansible.builtin.debug:
        msg: parameter-{{lookup('amazon.aws.aws_ssm', 'test.test', region= 'us-east-1')}}